
/**
 * Represents an item displayed on the Explore page grid.
 * Typically a Post or a Reel preview.
 */
export interface ExploreItem {
  /**
   * Unique ID of the content (e.g., post ID, reel ID).
   */
  id: string;
  /**
   * URL of the thumbnail image or video preview.
   */
  thumbnailUrl: string;
  /**
   * Type of content ('post' or 'reel').
   */
  type: 'post' | 'reel';
  /**
   * Optional: Number of likes, for potential overlay display on hover.
   */
  likes?: number;
  /**
   * Optional: Number of comments, for potential overlay display on hover.
   */
  commentsCount?: number;
    /**
   * Optional hint for AI-based image search or description generation.
   */
  imageHint?: string;
}


// --- Mock Data Simulation (Replace with actual Firestore calls) ---

const mockExploreItems: ExploreItem[] = Array.from({ length: 30 }).map((_, i) => {
    const isPost = Math.random() > 0.3; // 70% chance it's a post
    const seed = `explore_${i}_${Date.now()}`;
    return {
        id: `explore-item-${i}`,
        thumbnailUrl: `https://picsum.photos/seed/${seed}/300/300`, // Square thumbnails
        type: isPost ? 'post' : 'reel',
        likes: isPost ? Math.floor(Math.random() * 1000) : undefined, // Likes only for posts in this mock
        commentsCount: isPost ? Math.floor(Math.random() * 100) : undefined, // Comments only for posts
        imageHint: `explore content ${isPost ? 'post' : 'reel'} ${i % 5 === 0 ? 'popular' : ''}`, // Add some hints
    };
});

// --- End Mock Data Simulation ---


/**
 * Asynchronously retrieves content for the Explore page grid.
 * Simulates fetching popular or recommended posts/reels from Firestore.
 *
 * @param limit The maximum number of items to retrieve per batch (for pagination/infinite scroll).
 * @param startAfter // TODO: Add pagination logic
 * @returns A promise that resolves to an array of ExploreItem objects.
 */
export async function getExploreContent(limit: number = 21 /*, startAfter?: any */): Promise<ExploreItem[]> {
    console.log(`Simulating Firestore query for explore content (limit: ${limit})`);
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 600));

    // In real Firestore:
    // This would involve a more complex query or backend logic.
    // - Query posts and reels collections.
    // - Filter based on popularity (likes, comments, views), recency, user interests, etc.
    // - Might involve a separate 'exploreFeed' collection generated by backend processes.
    // - Implement proper pagination.

    // Mock implementation: Return a shuffled slice of the mock items.
    const shuffledItems = [...mockExploreItems].sort(() => 0.5 - Math.random());

    // TODO: Implement actual pagination based on startAfter
    return shuffledItems.slice(0, limit);
}
